# Created with YamlCreate.ps1 v2.2.10 $debug=NVS1.CRLF.5-1-19041-3031.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: binbat.live777
PackageVersion: 0.2.0
InstallerLocale: en-US
InstallerType: portable
Commands:
- live777
UpgradeBehavior: install
ReleaseDate: 2023-11-20
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/binbat/live777/releases/download/v0.3.1/live777-v0.3.1-i686-pc-windows-msvc.exe
  InstallerSha256: 1D351ADC4352FFB744ED2D9A13259849BFA07F8D4B8A33598E19B7F127D6B672
  Dependencies:
    PackageDependencies:
      - PackageIdentifier: Microsoft.VCRedist.2015+.x86
- Architecture: x64
  InstallerUrl: https://github.com/binbat/live777/releases/download/v0.2.0/live777-v0.2.0-x86_64-pc-windows-msvc.exe
  InstallerSha256: CF4914B9E034BD5520DB4F60E083CA44153C4F67F35CCF6C50260BB8A3C4FC05
  Dependencies:
    PackageDependencies:
      - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ManifestType: installer
ManifestVersion: 1.5.0
