# Created with YamlCreate.ps1 v2.2.10 $debug=NVS1.CRLF.5-1-19041-3031.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: binbat.whipinto
PackageVersion: 0.2.0
PackageLocale: en-US
Publisher: binbat
# PublisherUrl:
# PublisherSupportUrl:
# PrivacyUrl:
# Author:
PackageName: whiointo
# PackageUrl:
License: MIT
# LicenseUrl:
# Copyright:
# CopyrightUrl:
ShortDescription: whip
# Description:
# Moniker:
# Tags:
# ReleaseNotes:
# ReleaseNotesUrl:
# PurchaseUrl:
# InstallationNotes:
# Documentations:
ManifestType: defaultLocale
ManifestVersion: 1.5.0
