# Created with YamlCreate.ps1 v2.4.1 $debug=NVS1.CRLF.5-1-19041-4170.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: binbat.live777
PackageVersion: 0.4.1
InstallerType: portable
Commands:
- live777
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/binbat/live777/releases/download/v0.4.1/whepfrom-v0.4.1-i686-pc-windows-msvc.exe
  InstallerSha256: 25814D137D9764B85D4AB52652E97CF0F9D057660F817577082557C12982D2F5
ManifestType: installer
ManifestVersion: 1.6.0
